server:
    type: default
    applicationConnectors:
        -   type: http
            port: ${PORT:-8080}

goCardless:
    apiKey: ${GC_API_KEY:-}
    apiSecret: ${GC_API_SECRET:-}
    environment: ${GC_ENVIRONMENT:-sandbox}
