server:
    applicationConnectors:
        -   type: http
            port: ${PORT:-8080}

goCardless:
    accessToken: ${GC_ACCESS_TOKEN:-}
    webhookSecret: ${GC_WEBHOOK_SECRET:-}
    environment: ${GC_ENVIRONMENT:-sandbox}
