server:
    applicationConnectors:
        -   type: http
            port: ${PORT:-8080}
    requestLog:
        type: external
logging:
    type: external

goCardless:
    accessToken: ${GC_ACCESS_TOKEN:-}
    webhookSecret: ${GC_WEBHOOK_SECRET:-}
    environment: ${GC_ENVIRONMENT:-sandbox}
